# Configuration file for AppVeyor CI
configuration: Release

environment:
  VC_VARS_PATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat

  matrix:
    - QTDIR: C:\Qt\5.7\msvc2015
      CMAKE_GENERATOR: Visual Studio 14 2015
      WINDOWS_LIBS: C:\Windows\System32
      VC_VARS_ARCH: x86
    - QTDIR: C:\Qt\5.7\msvc2015_64
      CMAKE_GENERATOR: Visual Studio 14 2015 Win64
      WINDOWS_LIBS: C:\Windows\SysWOW64
      VC_VARS_ARCH: amd64

install:
- set PATH=%QTDIR%\bin;%PATH%
- set CMAKE_PREFIX_PATH=%QTDIR%\lib\cmake
- call "%VC_VARS_PATH%" %VC_VARS_ARCH%

before_build:
- utils\appveyor-before-build.bat

build:
  project: build\copyq.sln
  parallel: true

after_build:
- utils\appveyor-after-build.bat

artifacts:
- path: Bundle
  name: copyq
  type: WebDeployPackage
